### PR TITLE
Fixes #2 - disable linting on removed code

### LINKED ISSUE #2: Triggers rule: error  More than 1 blank line not allowed  no-multiple-empty-lines
[Test repo](https://github.com/rosskevin/my-relay-starter-kit) 

`npm install && npm run lint`

The following rule is being triggered as a side effect of omitting the code:

```
my-relay-starter-kit/src/App.js
  41:2  error  More than 1 blank line not allowed  no-multiple-empty-lines
```

``` javascript
const styles = (<style>
  html {
    font-family: Roboto, sans-serif;
    -webkit-font-smoothing: antialiased;
  }

  body {
    font-size: 15px;
    line-height: 24px;
  }

  body, h1, h2, h3, h4, h5, h6 {
    margin: 0;
  }

  a {
    color: #333;
    text-decoration: none;
  }

  a:hover {
    text-decoration: underline;
  }  // <- Line 41
</style>)
```

### PR DESCRIPTION
**Pull request by rosskevin**
It makes sense to keep the newlines instead of doing a multi-line replacement as I suggested in #2.  This will just disable linting over the removed code to disable false positives.

If you could merge and push a version, I would appreciate it!

### CODE REVIEW

**Comment by rosskevin** [comment]
hold one second, I have an update

**Comment by rosskevin** [comment]
ok, good to merge.

**Comment by krasimir** [comment]
Thanks!

**Comment by krasimir** [comment]
`0.3.3` released.

**Pull request merged**
